### ISSUE TITLE
Call stream.feed outside main

### ISSUE THREAD

**Issue by SwamiKannan** [KoljaB/RealtimeTTS#234]
I am building an agent which will "speak" the outputs outside the .py initiating the agent. I am guessing the stream.feed calls a multiprocessing function that requires the function to be called only under if __name__ == "__main__" function.

Is there a way to use the library to not use the __name__ == "__main__"? Am ok if it does not stream the output, but just play it after it has processed the text. Coqui generally needs to save the .wav file which I am not keen on.

**Comment by KoljaB** [comment]
That’s not possible with RealtimeTTS when using the CoquiEngine (other engines don’t need `if __name__ == "__main__"` protection).  

Here’s why:  
Local synthesis with a model like XTTS is resource-intensive. If you were to run RealtimeTTS in an app doing heavy processing too, you'd run into stuttering. The problem is Python’s multithreading doesn’t offer real parallelism. It’s just task-switching within the same core. That’s why spawning a separate process is necessary to ensure true parallelism.  

I get where you're coming from, but this library is built for fast, real-time TTS, and your use case seems outside of its scope. Changing it to bypass `__main__` protection would mean reworking a core design choice that rarely benefits others.  

Why do you need this? I’ve done tons of projects with RealtimeTTS and Coqui, and I’ve never hit a wall because of the `__main__` requirement. Maybe there’s another way to achieve what you’re aiming for without changing this.

**Comment by SwamiKannan** [comment]
It has just to do with the structure of my project. I understand where you're coming with this. Fair point ! Love the library !
