### ISSUE TITLE
About a paper

### ISSUE THREAD

**Issue by francqz31** [KoljaB/RealtimeTTS#8]
Hello Author, 
Really great Job with your 4 speech assistant related projects , to try bring the latency down as much as possible!

I was wondering have you see this paper , I think it claims the same , I still don't know which is faster , yours or theirs
https://arxiv.org/abs/2309.11210

Thanks in advance!

**Comment by KoljaB** [comment]
Thx a lot and yes, I am aware of that paper. 

They use a specialized LLM and synthesis method, which makes it hard to compare it to RealtimeTTS. Also they don't provide working code so far, so we can only do assumptions based on their paper.

They are able to do synthesis based on a lookahead of only two words. RealtimeTTS performs lookahead until a sentence separator is detected (like a comma), which will in nearly all cases be more than that mentioned two words. So we can quite safely assume that their approach allows for faster synthesis than what RealtimeTTS is able to provide. Notice that RealtimeTTS can't reduce it's synthesis context window further down, because all used engines would suffer in terms of synthesis quality doing that. 

They achieve a mean latency of less than 300 milliseconds but do not tell us on which hardware. RealtimeTTS achieves on my environment (Win 10, RTX 2080 SUPER, Ryzen 9 3900X, 32 GB RAM DDR4, 10Mbit internet connection) a latency of around 700 milliseconds with plain text (no LLM) for Azure and Coqui Engine, around 1 sec for Elevenlabs engine and around 100ms for system engine. You would need to add the individual LLM latency for inference of the first sentence fragment on top of that.

They also claim to maintain the audio quality without significant compromises. While I believe them and think this is possible, all other TTS engine can not do that, so I also think we need to do some extensive independent tests to see how good this approach really works for different use cases.
